### PR TITLE
Create 2022-08-02-Ukraine.md

### PR DESCRIPTION
**Pull request by fballiano**
As per https://github.com/OpenMage/magento-lts/pull/2325 I've created this file

### CODE REVIEW

**Review by sreichel — APPROVED** [review]

**Review by midlan — APPROVED** [review]

**Review by addison74 — APPROVED** [review]

**Review by sreichel — APPROVED** [review]

**Comment by addison74** [comment]
Maybe we should discuss receiving approval rights in this repository as well. If necessary, the number of approvals can be increased from the 2 as we have in OM to X. I see its usefulness to promote the new OM versions launched through the feed here. In the past I was not aware of Magento, but I appreciated an information note that a new version was launched, I felt like Santa Claus had come and I was curious to read the news. In addition, in all installations the users will find that we continue to make improvements to the code, perhaps many do not know about it.

**Comment by mark-netalico** [comment]
I agree with the sentiment of this, but just as an FYI it might be a little confusing to merchants who haven't gotten messages in awhile to receive something a bit off-topic. One of my merchants asked if they had gotten hacked or OpenMage had gotten hacked.

**Comment by addison74** [comment]
Maybe we should send an informative message to all OpenMage users based on this feature, what is happening with the project, future plans, new versions, etc. We can ask their opinions in the Discussion section. I doubt that there will be people disappointed by the information received.

**Comment by mark-netalico** [comment]
Yeah. I think we should keep this feature on topic as possible. We all remember the days of Magento and the Adobe spamming merchants with random things and migration scare warnings.

**Comment by sreichel** [comment]
> might be a little confusing to merchants who haven't gotten messages in awhile

Y. Can understand. I think there would be no/less confusion when we had adedd this in time. Ukraine war did not start 4 days ago ....

(@Flyingmana as mentioned somwhere else ... priveleges should be adjusted from time to time)

**Pull request merged**
