### PR TITLE
UPS XML API shutdown

### PR DESCRIPTION
**Pull request by fballiano**
dunno if it would be ok to directly add an email address for contacting...

### CODE REVIEW

**Comment by Flyingmana** [comment]
email probably only of it is a contact email with openMage domain, do we already have one besides security?

**Comment by fballiano** [comment]
I've no idea, let's leave it as it is then, if that's ok with you

**Comment by fballiano** [comment]
shall we merge and send the notification?

**Review by Flyingmana — APPROVED** [review]

**Comment by Flyingmana** [comment]
lets hope the build still works 😅 else I will fix it later today

**Comment by fballiano** [comment]
there's no way we can get another approval here :-D

**Comment by Flyingmana** [comment]
its now listed on the used notification feed https://www.openmage.org/Web_Notifications/notifications_v1.rss

**Comment by fballiano** [comment]
@Flyingmana I think the severity was wrong because I don't see the notification popping up in the backend and it doesn't have the severity badge

Screenshot 2024-03-17 alle 09 18 04

I've no idea how to fix it

**Comment by Flyingmana** [comment]
can you check the code behind the badge? its probably a simple mapping

**Comment by fballiano** [comment]
oh... from what I can see I had to use severity 1 for the most critical notification....... @Flyingmana should we now delete this message and create a new one for everybody to get a new notification?

**Comment by Flyingmana** [comment]
deleting it will not remove the notification from the systems who already loaded it, but I guess its needed.

**Comment by fballiano** [comment]
no it won't delete it but this one doesn't even show so it's kinda useless.

yes it was 1:
Screenshot 2024-03-17 alle 09 22 29

**Pull request merged**
